baseurl = "your-site-address"
title = "your-site-name"
languageCode = "ko-KR"

theme = "hello-programmer"

# Pagination
paginate = 2

[author]
    name = "your-name"
    email = "your-email"

[Params]
    disqusShortname = "XXXX"
    googleAnalytics = "UA-XXXXXXXX-X"